# Generated by Django 3.1.5 on 2021-01-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191216_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='room',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
